package com.jellypudding.offlineclient.modules.hunting;

import com.jellypudding.offlineclient.OfflineClient;
import com.jellypudding.offlineclient.event.Subscribe;
import com.jellypudding.offlineclient.event.events.ChunkDataEvent;
import com.jellypudding.offlineclient.event.events.PacketReceiveEvent;
import com.jellypudding.offlineclient.event.events.Render3DEvent;
import com.jellypudding.offlineclient.event.events.TickEvent;
import com.jellypudding.offlineclient.module.Category;
import com.jellypudding.offlineclient.module.Module;
import com.jellypudding.offlineclient.render.DrawBatch;
import com.jellypudding.offlineclient.setting.BoolSetting;
import com.jellypudding.offlineclient.setting.ColorSetting;
import com.jellypudding.offlineclient.setting.NumberSetting;
import com.jellypudding.offlineclient.util.ChatUtil;
import com.jellypudding.offlineclient.util.ChunkOrigin;
import com.jellypudding.offlineclient.util.ColorUtil;
import com.jellypudding.offlineclient.util.WorldWatch;
import net.minecraft.SharedConstants;
import net.minecraft.core.BlockPos;
import net.minecraft.core.SectionPos;
import net.minecraft.network.protocol.game.ClientboundBlockUpdatePacket;
import net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket;
import net.minecraft.tags.FluidTags;
import net.minecraft.util.Mth;
import net.minecraft.world.attribute.EnvironmentAttributes;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.chunk.LevelChunk;
import net.minecraft.world.level.chunk.LevelChunkSection;
import net.minecraft.world.level.material.FluidState;
import net.minecraft.world.phys.AABB;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Queue;
import java.util.Set;
import java.util.concurrent.ConcurrentLinkedQueue;

// Judges chunks fresh or old as they arrive. The palettes the server sent come first. A chunk
// they leave open falls to its liquid. Liquid already flowing on arrival means it was loaded
// from disk and a flow that starts right after means it was just generated. An old chunk
// whose palettes still list a block that is gone changed since the server loaded it. Only
// someone nearby keeps a chunk loaded and changes it.
public final class NewChunks extends Module {

    private static final int MAX_CHUNKS = 16384;

    // The tint inside a square next to its outline.
    private static final float FILL_SHARE = 40 / 255f;

    // The chunks the server ticks for you may change before they are sent. The margin allows
    // for a server that counts that distance one ring wider.
    private static final int OWN_TICKING_MARGIN = 1;

    // A changed chunk this close to one already posted belongs to the same group of players.
    private static final int ALERT_GAP_CHUNKS = 8;
    private static final int MAX_ALERTS = 64;

    private final BoolSetting paletteCheck = new BoolSetting("Palette check",
        "Judges each chunk by the order of the block and biome lists the server sent with it. "
            + "Needs a server on 1.18 or newer.", true);
    private final BoolSetting liquidCheck = new BoolSetting("Liquid check",
        "Judges the chunks the palettes leave open by whether their water and lava were already "
            + "flowing when they arrived.", true);
    private final NumberSetting settle = new NumberSetting("Settle time",
        "How long after a chunk lands a liquid flow still counts as fresh.", 60, 5, 300, 5, "s")
        .min(1).under(liquidCheck);
    private final NumberSetting minSpread = new NumberSetting("Min spread",
        "How far a flow must have run from its source before it proves a chunk old. Raise it on servers that tick chunks before sending them.",
        3, 1, 7, 1, " blocks").min(1).max(7).under(liquidCheck);
    private final BoolSetting activityCheck = new BoolSetting("Activity check",
        "Marks old chunks whose blocks changed since the server loaded them. Someone is near them "
            + "or was moments ago. Only chunks past the server's simulation distance from you can be read.",
        true);
    private final ColorSetting activeColor = new ColorSetting("Active colour",
        "Colour of the chunks that changed since the server loaded them.", 45, false)
        .under(activityCheck);
    private final BoolSetting activityChat = new BoolSetting("Activity chat",
        "Posts in chat when a changed chunk turns up away from any posted before.", true)
        .under(activityCheck);
    private final BoolSetting oldVersions = new BoolSetting("Old versions",
        "Marks chunks first generated by a game version older than 1.18 in their own colour. "
            + "In the nether that means older than 1.16 and in the End older than 1.13.", true);
    private final ColorSetting oldVersionColor = new ColorSetting("Old version colour",
        "Colour of the chunks first generated by an older game version.", 280, false)
        .under(oldVersions);
    private final ColorSetting newColor = new ColorSetting("New colour",
        "Colour of the fresh chunks. The server generated them moments before it sent them.",
        0, false);
    private final BoolSetting showOld = new BoolSetting("Show old chunks",
        "Also draws the chunks judged old since you switched this on.", false);
    private final ColorSetting oldColor = new ColorSetting("Old colour",
        "Colour of the old chunks. The server loaded them from its save.",
        220, false).under(showOld);
    private final BoolSetting showUnjudged = new BoolSetting("Show unjudged",
        "Also draws the chunks that arrived without anything to judge them by.", false);
    private final ColorSetting unjudgedColor = new ColorSetting("Unjudged colour",
        "Colour of the chunks with no verdict.", 60, false)
        .under(showUnjudged);
    private final NumberSetting opacity = new NumberSetting("Opacity",
        "How solid the squares are drawn.", 75, 10, 100, 5, "%").min(1).max(100);
    private final BoolSetting fill = new BoolSetting("Fill",
        "Adds a faint tint inside each square.", true);
    private final BoolSetting followHeight = new BoolSetting("Follow height",
        "Draws the squares at your own height instead of a fixed one.", true);
    private final NumberSetting drawHeight = new NumberSetting("Height",
        "The height the squares sit at.", 64, -64, 320, 1)
        .min(-2048).max(2048).unless(followHeight);
    private final NumberSetting distance = new NumberSetting("Distance",
        "How far away a chunk may be and still be drawn.", 16, 4, 64, 1, " chunks")
        .min(1);
    private final BoolSetting showReasons = new BoolSetting("Show reasons",
        "Outlines the section or the liquid block that decided each verdict.", false);
    private final BoolSetting logChunks = new BoolSetting("Log chunks",
        "Writes every verdict to the game log.", false);
    private final BoolSetting notice = new BoolSetting("Notice",
        "Explains the limits in chat when you switch this on.", true);

    // The verdicts never overlap. A chunk in none of them is unjudged.
    private final Set<Long> newChunks = new HashSet<>();
    private final Set<Long> oldChunks = new HashSet<>();
    private final Set<Long> oldVersionChunks = new HashSet<>();
    private final Set<Long> activeChunks = new HashSet<>();
    // The changed chunks posted in chat. Newest last.
    private final Deque<Long> alerted = new ArrayDeque<>();

    // Every chunk that landed whilst this ran mapped to its tick in arrival order.
    private final Map<Long, Integer> watched = new LinkedHashMap<>();

    // Filled from the network thread and drained on the next tick.
    private final Queue<BlockPos> flowing = new ConcurrentLinkedQueue<>();

    // The section or liquid block that decided each verdict. Drawn by the Show reasons setting.
    private final Map<Long, AABB> reasons = new HashMap<>();

    // The chunks in range of the last rebuild kept apart by verdict. Colours are
    // resolved at draw time because a rainbow setting moves every frame.
    private final List<Long> visibleNew = new ArrayList<>();
    private final List<Long> visibleOld = new ArrayList<>();
    private final List<Long> visibleOldVersion = new ArrayList<>();
    private final List<Long> visibleActive = new ArrayList<>();
    private final List<Long> visibleUnjudged = new ArrayList<>();

    private long visibleAt = Long.MIN_VALUE;
    private int revision;
    private int drawnRevision = -1;
    private int drawnLayout = -1;

    private final WorldWatch world = new WorldWatch();
    private int ticks;

    public NewChunks() {
        super("NewChunks", "Marks fresh and old chunks that load whilst this is on.",
            Category.HUNTING);
        addSettings(paletteCheck, liquidCheck, settle, minSpread, activityCheck, activeColor,
            activityChat, oldVersions, oldVersionColor,
            newColor, showOld, oldColor, showUnjudged, unjudgedColor, opacity, fill, followHeight,
            drawHeight, distance, showReasons, logChunks, notice);
        searchTags("new chunks", "fresh terrain", "old chunks", "palette", "exploit", "activity",
            "online player");
    }

    @Override
    public String getSuffix() {
        int judged = newChunks.size() + oldChunks.size() + oldVersionChunks.size() + activeChunks.size();
        String suffix = newChunks.size() + " new " + oldChunks.size() + " old";
        if (!oldVersionChunks.isEmpty()) {
            suffix += " " + oldVersionChunks.size() + " old version";
        }
        if (!activeChunks.isEmpty()) {
            suffix += " " + activeChunks.size() + " active";
        }
        return suffix + " " + Math.max(0, watched.size() - judged) + " unjudged";
    }

    @Override
    protected void onEnable() {
        reset();
        world.accept();
        if (notice.isOn()) {
            ChatUtil.message("§bNewChunks §7only judges chunks that load whilst it is on. "
                + "Switch it on before you explore. The palette check needs a server on 1.18 or newer. "
                + "The liquid check can call a fresh chunk old on a server that ticks chunks before "
                + "sending them. Raise Min spread if that happens.");
            if (activityCheck.isOn() && inGame() && readableRings() <= 0) {
                ChatUtil.message("§bNewChunks §7cannot run the activity check here. The server simulates "
                    + "every chunk it sends you.");
            }
        }
    }

    @Override
    protected void onDisable() {
        reset();
    }

    private void reset() {
        newChunks.clear();
        oldChunks.clear();
        oldVersionChunks.clear();
        activeChunks.clear();
        alerted.clear();
        watched.clear();
        reasons.clear();
        flowing.clear();
        clearVisible();
        visibleAt = Long.MIN_VALUE;
        revision++;
        ticks = 0;
    }

    // Chunk coordinates mean something different in every world.
    private void syncWorld() {
        if (world.changed()) {
            reset();
        }
    }

    // The oldest chunk drops once the store is full.
    private void remember(long key) {
        watched.put(key, ticks);
        revision++;
        if (watched.size() <= MAX_CHUNKS) {
            return;
        }
        Iterator<Long> iterator = watched.keySet().iterator();
        while (watched.size() > MAX_CHUNKS && iterator.hasNext()) {
            long eldest = iterator.next();
            iterator.remove();
            newChunks.remove(eldest);
            oldChunks.remove(eldest);
            oldVersionChunks.remove(eldest);
            activeChunks.remove(eldest);
            reasons.remove(eldest);
        }
    }

    // Every later packet is still waiting. No flow update has been written into the chunk
    // and its palettes hold the server's order.
    @Subscribe
    private void onChunkData(ChunkDataEvent event) {
        syncWorld();
        LevelChunk chunk = event.getChunk();
        long key = chunk.getPos().pack();
        if (watched.containsKey(key)) {
            // A second arrival keeps the first verdict.
            return;
        }
        remember(key);
        judge(chunk, key);
    }

    // An old version is judged first. A chunk from before 1.18 has its sections below nought
    // built anew the first time it loads and their palettes read fresh. Without its own
    // colour an old version chunk counts as old.
    private void judge(LevelChunk chunk, long key) {
        int oldSection = ChunkOrigin.oldVersionSection(chunk);
        if (oldSection >= 0) {
            boolean own = oldVersions.isOn();
            mark(own ? oldVersionChunks : oldChunks, key, sectionBox(chunk, oldSection),
                own ? "old version" : "old");
            return;
        }
        boolean readPalettes = paletteCheck.isOn() || activityCheck.isOn();
        ChunkOrigin.Finding palettes = readPalettes ? ChunkOrigin.readPalettes(chunk) : null;
        if (palettes != null && palettes.age() == ChunkOrigin.Age.OLD && activityCheck.isOn()
            && pastOwnTicking(chunk)) {
            int changed = ChunkOrigin.changedSection(chunk);
            if (changed >= 0) {
                mark(activeChunks, key, sectionBox(chunk, changed), "active");
                if (activityChat.isOn() && farFromAlerts(key)) {
                    ChatUtil.message("§bNewChunks §7found blocks changed in the chunk at §f"
                        + chunk.getPos().getMiddleBlockX() + " " + chunk.getPos().getMiddleBlockZ()
                        + " §7since the server loaded it. Someone is near it or was moments ago.");
                }
                return;
            }
        }
        if (palettes != null && paletteCheck.isOn()) {
            boolean fresh = palettes.age() == ChunkOrigin.Age.FRESH;
            mark(fresh ? newChunks : oldChunks, key, sectionBox(chunk, palettes.section()),
                fresh ? "new" : "old");
            return;
        }
        if (liquidCheck.isOn()) {
            BlockPos found = findFlowingLiquid(chunk, minSpread.getInt());
            if (found != null) {
                mark(oldChunks, key, DrawBatch.blockBox(found), "old");
            }
        }
    }

    // How many rings of the chunks the server sends lie past the ones it ticks around you.
    private int readableRings() {
        return mc.player.connection.serverChunkRadius - ownTickingRings();
    }

    private int ownTickingRings() {
        return mc.player.connection.serverSimulationDistance + OWN_TICKING_MARGIN;
    }

    // Remembers the chunk when it is far enough from every earlier post to earn one.
    private boolean farFromAlerts(long key) {
        for (long earlier : alerted) {
            if (Mth.chessboardDistance(ChunkPos.getX(earlier), ChunkPos.getZ(earlier),
                ChunkPos.getX(key), ChunkPos.getZ(key)) < ALERT_GAP_CHUNKS) {
                return false;
            }
        }
        alerted.addLast(key);
        if (alerted.size() > MAX_ALERTS) {
            alerted.removeFirst();
        }
        return true;
    }

    private boolean pastOwnTicking(LevelChunk chunk) {
        return mc.player.chunkPosition().getChessboardDistance(chunk.getPos()) > ownTickingRings();
    }

    private void mark(Set<Long> verdict, long key, AABB reason, String name) {
        verdict.add(key);
        reasons.put(key, reason);
        revision++;
        if (logChunks.isOn()) {
            OfflineClient.LOG.info("NewChunks {} chunk at {} {}", name,
                SectionPos.sectionToBlockCoord(ChunkPos.getX(key)),
                SectionPos.sectionToBlockCoord(ChunkPos.getZ(key)));
        }
    }

    private boolean judged(long key) {
        return newChunks.contains(key) || oldChunks.contains(key) || oldVersionChunks.contains(key)
            || activeChunks.contains(key);
    }

    private static AABB sectionBox(LevelChunk chunk, int section) {
        double x = chunk.getPos().getMinBlockX();
        double y = SectionPos.sectionToBlockCoord(chunk.getSectionYFromSectionIndex(section));
        double z = chunk.getPos().getMinBlockZ();
        return new AABB(x, y, z, x + SectionPos.SECTION_SIZE, y + SectionPos.SECTION_SIZE,
            z + SectionPos.SECTION_SIZE);
    }

    // Fired on the netty thread.
    @Subscribe
    private void onPacketReceive(PacketReceiveEvent event) {
        if (event.getPacket() instanceof ClientboundBlockUpdatePacket update) {
            noteFlow(update.getPos(), update.getBlockState());
        } else if (event.getPacket() instanceof ClientboundSectionBlocksUpdatePacket update) {
            update.runUpdates(this::noteFlow);
        }
    }

    private void noteFlow(BlockPos pos, BlockState state) {
        if (isFlowing(state)) {
            flowing.add(pos.immutable());
        }
    }

    @Subscribe
    private void onTick(TickEvent event) {
        if (!inGame()) {
            return;
        }
        syncWorld();
        ticks++;

        // A flow that turns up after the chunk landed means the chunk is fresh.
        boolean judgeFlows = liquidCheck.isOn();
        int window = settle.getInt() * SharedConstants.TICKS_PER_SECOND;
        BlockPos pos;
        while ((pos = flowing.poll()) != null) {
            long key = ChunkPos.pack(pos);
            Integer seen = watched.get(key);
            if (!judgeFlows || seen == null || judged(key)) {
                continue;
            }
            if (ticks - seen <= window) {
                mark(newChunks, key, DrawBatch.blockBox(pos), "new");
            }
        }
    }

    // The first flowing liquid in the chunk or null. The palette test is only a prefilter
    // and every hit is confirmed against the real blocks.
    private static BlockPos findFlowingLiquid(LevelChunk chunk, int spread) {
        boolean fastLava = chunk.getLevel().environmentAttributes().getDimensionValue(EnvironmentAttributes.FAST_LAVA);
        LevelChunkSection[] sections = chunk.getSections();
        int minY = chunk.getMinY();
        int minX = chunk.getPos().getMinBlockX();
        int minZ = chunk.getPos().getMinBlockZ();
        for (int i = 0; i < sections.length; i++) {
            LevelChunkSection section = sections[i];
            if (section == null || section.hasOnlyAir() || !section.hasFluid()
                || !section.maybeHas(NewChunks::isFlowing)) {
                continue;
            }
            for (int y = 0; y < 16; y++) {
                for (int x = 0; x < 16; x++) {
                    for (int z = 0; z < 16; z++) {
                        if (spreadOf(section.getBlockState(x, y, z), fastLava) >= spread) {
                            return new BlockPos(minX + x, minY + i * 16 + y, minZ + z);
                        }
                    }
                }
            }
        }
        return null;
    }

    private static boolean isFlowing(BlockState state) {
        FluidState fluid = state.getFluidState();
        return !fluid.isEmpty() && !fluid.isSource();
    }

    // How many blocks a flow has run from its source. A source is nought and falling liquid
    // reads as one. Water loses a level for each block. Lava loses two unless the dimension
    // makes it fast.
    private static int spreadOf(BlockState state, boolean fastLava) {
        FluidState fluid = state.getFluidState();
        if (fluid.isEmpty() || fluid.isSource()) {
            return 0;
        }
        int levels = Math.max(1, 8 - fluid.getAmount());
        return fluid.is(FluidTags.LAVA) && !fastLava ? (levels + 1) / 2 : levels;
    }

    @Subscribe
    private void onRender3D(Render3DEvent event) {
        if (!inGame()) {
            return;
        }
        int centerX = mc.player.chunkPosition().x();
        int centerZ = mc.player.chunkPosition().z();
        long here = ChunkPos.pack(centerX, centerZ);
        int layout = layoutKey();
        if (here != visibleAt || revision != drawnRevision || layout != drawnLayout) {
            rebuildVisible(centerX, centerZ);
            visibleAt = here;
            drawnRevision = revision;
            drawnLayout = layout;
        }

        double y = followHeight.isOn() ? mc.player.getY() : drawHeight.getValue();
        float share = opacity.getFloat() / 100f;
        DrawBatch batch = event.getBatch();
        drawAll(batch, visibleNew, ColorUtil.fade(newColor.getColor(), share), y);
        drawAll(batch, visibleOld, ColorUtil.fade(oldColor.getColor(), share), y);
        drawAll(batch, visibleOldVersion, ColorUtil.fade(oldVersionColor.getColor(), share), y);
        drawAll(batch, visibleActive, ColorUtil.fade(activeColor.getColor(), share), y);
        drawAll(batch, visibleUnjudged, ColorUtil.fade(unjudgedColor.getColor(), share), y);

        if (showReasons.isOn()) {
            markReasons(batch, visibleNew, newColor.getColor());
            markReasons(batch, visibleOld, oldColor.getColor());
            markReasons(batch, visibleOldVersion, oldVersionColor.getColor());
            markReasons(batch, visibleActive, activeColor.getColor());
        }
    }

    // Draws what proved the verdict. Lets you check the call yourself.
    private void markReasons(DrawBatch batch, List<Long> chunks, int color) {
        for (long key : chunks) {
            AABB box = reasons.get(key);
            if (box != null) {
                batch.outlineBox(box, color, true);
            }
        }
    }

    private void drawAll(DrawBatch batch, List<Long> chunks, int color, double y) {
        for (long key : chunks) {
            square(batch, ChunkPos.getX(key) * 16, ChunkPos.getZ(key) * 16, y, color);
        }
    }

    private void clearVisible() {
        visibleNew.clear();
        visibleOld.clear();
        visibleOldVersion.clear();
        visibleActive.clear();
        visibleUnjudged.clear();
    }

    // The settings that decide which chunks land in the visible lists.
    private int layoutKey() {
        return (showOld.isOn() ? 1 : 0) | (showUnjudged.isOn() ? 2 : 0) | (oldVersions.isOn() ? 4 : 0)
            | (activityCheck.isOn() ? 8 : 0) | distance.getInt() << 4;
    }

    // Walks whichever is smaller of the square around the player and the whole store. A
    // long draw distance then costs no more than the chunks there are.
    private void rebuildVisible(int centerX, int centerZ) {
        clearVisible();
        int limit = distance.getInt();
        long side = 2L * limit + 1;
        if (side * side > watched.size()) {
            for (long key : watched.keySet()) {
                if (Math.abs(ChunkPos.getX(key) - centerX) <= limit
                    && Math.abs(ChunkPos.getZ(key) - centerZ) <= limit) {
                    sortVisible(key);
                }
            }
            return;
        }
        for (int x = centerX - limit; x <= centerX + limit; x++) {
            for (int z = centerZ - limit; z <= centerZ + limit; z++) {
                sortVisible(ChunkPos.pack(x, z));
            }
        }
    }

    private void sortVisible(long key) {
        if (newChunks.contains(key)) {
            visibleNew.add(key);
        } else if (oldChunks.contains(key)) {
            if (showOld.isOn()) {
                visibleOld.add(key);
            }
        } else if (activeChunks.contains(key)) {
            if (activityCheck.isOn()) {
                visibleActive.add(key);
            }
        } else if (oldVersionChunks.contains(key)) {
            if (oldVersions.isOn()) {
                visibleOldVersion.add(key);
            }
        } else if (showUnjudged.isOn() && watched.containsKey(key)) {
            visibleUnjudged.add(key);
        }
    }

    // A flat box has no edges to draw.
    private void square(DrawBatch batch, double x1, double z1, double y, int color) {
        double x2 = x1 + 16;
        double z2 = z1 + 16;
        batch.flatRect(x1, z1, x2, z2, y, color, true);
        if (fill.isOn()) {
            batch.solidBox(new AABB(x1, y, z1, x2, y + 0.02, z2),
                ColorUtil.fade(color, FILL_SHARE), true);
        }
    }
}
